Have the bootstrap script fail to start server if ~/.zserv_fail_start exists

diff --git a/zserv/bin/zserv-bootstrap b/zserv/bin/zserv-bootstrap
--- a/zserv/bin/zserv-bootstrap
+++ b/zserv/bin/zserv-bootstrap
@@ -185,7 +185,12 @@ while read line; do
     set $line
     case "$1" in
         "START")
-            runserver && echo "!ZSERV START SUCCESS" || echo "!ZSERV START FAILURE"
+            # For testing
+            if [[ -e $HOME/.zserv_fail_start ]]; then
+                echo "!ZSERV START FAILURE"
+            else
+                runserver && echo "!ZSERV START SUCCESS" || echo "!ZSERV START FAILURE"
+            fi
             ;;
         "INFO")
             info
