Send base64 encoded bks keystores instead of pem certs to client.

diff --git a/zserv/bin/zserv-bootstrap b/zserv/bin/zserv-bootstrap
--- a/zserv/bin/zserv-bootstrap
+++ b/zserv/bin/zserv-bootstrap
@@ -10,11 +10,11 @@ SHARE_PATH="$THIS_DIR/../data"
 SERVER_PRIV="$DATA_DIR/certs/server_private.pem" 
 SERVER_PUB="$DATA_DIR/certs/server_public.pem" 
 
-echo "ZSERV HELLO"
-trap "echo 'ZSERV BYE'" EXIT
+echo "!ZSERV HELLO"
+trap "echo '!ZSERV BYE'" EXIT
 
 die() {
-    echo "ZSERV ERROR $*"
+    echo "!ZSERV ERROR $*"
     exit 1
 }
 
@@ -74,7 +74,7 @@ cleanup_certs() {
         f="$DATA_DIR/certs/$file"
         [[ -e $f ]] && rm -f "$f"
     done
-    [[ -d "$DATA_DIR/certs/" ]] || mkdir "$DATA_DIR/certs"
+    [[ -d "$DATA_DIR/certs/" ]] || mkdir -p --mode=0700 "$DATA_DIR/certs"
 }
 
 mkcerts() {
@@ -83,25 +83,19 @@ mkcerts() {
 }
 
 getbks() {
-    [[ -e "$1" ]] || die "The server failed to specify the public cert."
-    CERT_BKS="$1.bks"
-    KEYSTORE="$1.keystore"
+    [[ -e "$1" ]] || die "Public cert not found."
+    KEYSTORE="$1.bks"
 
-    if [[ ! -e "$CERT_BKS" ]]; then
+    if [[ ! -e "$KEYSTORE" ]]; then
         yes | keytool -importcert -trustcacerts -keystore $KEYSTORE \
-            -storetype bks -storepass "<BLANK>" -file $1 \
+            -storetype bks -storepass "<BLANK>" -file <(openssl x509 -in $1) \
             -provider org.bouncycastle.jce.provider.BouncyCastleProvider \
             -providerpath $SHARE_PATH/bcprov/bcprov.jar >/dev/null 2>&1
 
-        keytool -exportcert -rfc -keystore $KEYSTORE \
-            -storetype bks -storepass "<BLANK>"  \
-            -provider org.bouncycastle.jce.provider.BouncyCastleProvider \
-            -providerpath $SHARE_PATH/bcprov/bcprov.jar > $CERT_BKS 2>/dev/null
-        rm $KEYSTORE
     fi
-    echo "ZSERV CERT BEGIN"
-    cat "$CERT_BKS"
-    echo "ZSERV CERT END"
+    echo "!ZSERV CERT BEGIN"
+    base64 "$KEYSTORE"
+    echo "!ZSERV CERT END"
 }
 
 runserver() {
@@ -131,43 +125,43 @@ runserver() {
 
 info() {
     if ! isrunning; then
-        echo "ZSERV INFO FAILED"
+        echo "!ZSERV INFO FAILED"
         return
     fi
     . $INFO
-    echo "ZSERV INFO BEGIN"
-    echo "ZSERV VERSION $VERSION"
-    echo "ZSERV HOST $HOST"
-    echo "ZSERV PORT $PORT"
+    echo "!ZSERV INFO BEGIN"
+    echo "!ZSERV VERSION $VERSION"
+    echo "!ZSERV HOST $HOST"
+    echo "!ZSERV PORT $PORT"
     getbks $CERT_PUB
-    echo "ZSERV INFO END"
+    echo "!ZSERV INFO END"
 }
 
 
 while read line; do
     case "$line" in
         "START")
-            runserver && echo "ZSERV START SUCCESS" || echo "ZSERV START FAILURE"
+            runserver && echo "!ZSERV START SUCCESS" || echo "!ZSERV START FAILURE"
             ;;
         "INFO")
             info
             ;;
         "STOP")
-            killserver && echo "ZSERV STOP SUCCESS" || echo "ZSERV STOP FAILURE"
+            killserver && echo "!ZSERV STOP SUCCESS" || echo "!ZSERV STOP FAILURE"
             ;;
         "ISRUNNING")
-            isrunning && echo "ZSERV ISRUNNING TRUE" || echo "ZSERV ISRUNNING FALSE"
+            isrunning && echo "!ZSERV ISRUNNING TRUE" || echo "!ZSERV ISRUNNING FALSE"
             ;;
         "RESTART")
             {
                 killserver && runserver
-            } && echo "ZSERV RESTART SUCCESS" || echo "ZSERV RESTART FAILURE"
+            } && echo "!ZSERV RESTART SUCCESS" || echo "!ZSERV RESTART FAILURE"
             ;;
         "BYE")
             break;
             ;;
         *)
-            echo "ZSERV INVALID_INPUT"
+            echo "!ZSERV INVALID_INPUT"
             ;;
     esac
 done
