Fix bug starting zserv-bootstrap in a different dir.

diff --git a/zserv/bin/zserv-bootstrap b/zserv/bin/zserv-bootstrap
--- a/zserv/bin/zserv-bootstrap
+++ b/zserv/bin/zserv-bootstrap
@@ -1,5 +1,5 @@
 #!/bin/bash
-THIS_DIR="$(dirname ${BASH_SOURCE[0]})"
+THIS_DIR="$(readlink -f $(dirname ${BASH_SOURCE[0]}))"
 export PATH="$PATH:$THIS_DIR"
 DATA_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/zephyr-server/"
 # This should be safe as dtach makes its own socket and will fail if one
@@ -113,7 +113,10 @@ runserver() {
             cleanup_certs
             mkcerts
         fi
-        zserv-dtach $SOCKET --ssl --key=$SERVER_PRIV --cert=$SERVER_PUB || die "Failed to start server."
+        (
+            cd $THIS_DIR
+            ./zserv-dtach $SOCKET --ssl --key=$SERVER_PRIV --cert=$SERVER_PUB || die "Failed to start server."
+        )
     fi
 
     # Wait for the file to exist and be readable.
