Allow getting the pem cert

diff --git a/zserv/bin/zserv-bootstrap b/zserv/bin/zserv-bootstrap
--- a/zserv/bin/zserv-bootstrap
+++ b/zserv/bin/zserv-bootstrap
@@ -89,22 +89,6 @@ mkcerts() {
     openssl req -subj "/CN=ZSERV/" -new -x509 -key $SERVER_PRIV -out $SERVER_PUB >/dev/null 2>&1
 }
 
-getbks() {
-    [[ -e "$1" ]] || die "Public cert not found."
-    KEYSTORE="$1.bks"
-
-    if [[ ! -e "$KEYSTORE" ]]; then
-        yes | keytool -importcert -trustcacerts -keystore $KEYSTORE \
-            -storetype bks -storepass "<BLANK>" -file <(openssl x509 -in $1) \
-            -provider org.bouncycastle.jce.provider.BouncyCastleProvider \
-            -providerpath $SHARE_PATH/bcprov/bcprov.jar >/dev/null 2>&1
-
-    fi
-    echo "!ZSERV CERT BEGIN"
-    base64 "$KEYSTORE"
-    echo "!ZSERV CERT END"
-}
-
 runserver() {
     if ! isrunning; then
         if [[ ! -r "$DATA_DIR/certs/server_public.pem" ]]; then
@@ -145,6 +129,37 @@ info() {
     echo "!ZSERV INFO END"
 }
 
+getcert() {
+    [[ -e "$1" ]] || die "Public cert not found."
+    case $2 in 
+        "BKS") getbks $1 ;;
+        "PEM") getpem $1 ;;
+        *) echo "!ZSERV GET CERT $2 INVALID" ;;
+    esac
+}
+            
+getpem() {
+    echo "!ZSERV CERT BEGIN"
+    cat $1
+    echo "!ZSERV CERT END"
+}
+
+getbks() {
+    KEYSTORE="$1.bks"
+
+    if [[ ! -e "$KEYSTORE" ]]; then
+        yes | keytool -importcert -trustcacerts -keystore $KEYSTORE \
+            -storetype bks -storepass "<BLANK>" -file <(openssl x509 -in $1) \
+            -provider org.bouncycastle.jce.provider.BouncyCastleProvider \
+            -providerpath $SHARE_PATH/bcprov/bcprov.jar >/dev/null 2>&1
+
+    fi
+    echo "!ZSERV CERT BEGIN"
+    base64 "$KEYSTORE"
+    echo "!ZSERV CERT END"
+}
+
+
 get() {
     if ! isrunning; then
         echo "!ZSERV GET FAILED"
@@ -158,16 +173,12 @@ get() {
             echo "!ZSERV HOST $HOST" ;;
         "PORT")
             echo "!ZSERV PORT $PORT" ;;
-        "CERT") getbks $CERT_PUB ;;
+        "CERT") getcert $CERT_PUB $2 ;;
         *)
             echo "!ZSERV GET $1 INVALID"
             ;;
     esac
 }
-
-
-
-
 
 while read line; do
     set $line
